### ISSUE TITLE
Setting fps

### ISSUE THREAD

**Issue by quockhanh1198** [JJFourie/ESP32Cam-MQTT-SPIFFS-PIR#2]
Hi @JJFourie , I read and feel your project is very fantastic, I want to config fps and setting but I don't know to do it, Can you help me, bro ?

**Comment by JJFourie** [comment]
Thanks!
I did not do anything with FPS, so I can't really say anything about it.
Maybe you can learn from what this guy did in the [Espressif github](https://github.com/espressif/esp32-camera/issues/15#issuecomment-455886304), he managed to get 60 FPS in CIF and 30 FPS in VGA/SVGA.

You can also have a look at the paragraph on frame rates in the [OV2640 writeup](https://www.uctronics.com/download/cam_module/OV2640DS.pdf).
